btest:
	g++ -std=c++11 -Wall -Werror -Wuninitialized -I../gtest*/include/ btest.cpp libgtest.a -lpthread -o btest

btree:
	g++ -std=c++11 -Wall -Werror -Wuninitialized -c btree.h

test:
	g++ -std=c++11 -Wall -Werror -Wuninitialized test.cpp -o test


